name: Update Frida Gum Devkits

on:
  schedule:
    - cron: "0 * * * *"  # Check hourly
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_update:
    runs-on: ubuntu-latest
    outputs:
      latest_version: ${{ steps.get_version.outputs.version }}
      has_update: ${{ steps.compare.outputs.has_update }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest Frida version
        id: get_version
        run: |
          version=$(curl -s https://api.github.com/repos/frida/frida/releases/latest | jq -r .tag_name)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Compare with current VERSION
        id: compare
        run: |
          latest="${{ steps.get_version.outputs.version }}"
          current=$(cat VERSION 2>/dev/null || echo "none")
          echo "Current: $current | Latest: $latest"
          if [ "$latest" != "$current" ]; then
            echo "has_update=true" >> $GITHUB_OUTPUT
          else
            echo "has_update=false" >> $GITHUB_OUTPUT
          fi

  update_frida:
    needs: check_update
    if: needs.check_update.outputs.has_update == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Frida Gum Devkits
        run: |
          version="${{ needs.check_update.outputs.latest_version }}"
          echo "Updating to $version"

          mkdir -p tmp
          cd tmp

          for arch in arm arm64 x86 x86_64; do
            url="https://github.com/frida/frida/releases/download/${version}/frida-gum-devkit-${version}-android-${arch}.tar.xz"
            echo "Downloading $url"
            curl -sL "$url" | tar xJf -

            src="frida-gum-devkit-${version}-android-${arch}"
            mkdir -p ../android-${arch}
            mv "$src/include" ../android-${arch}/
            mv "$src/lib" ../android-${arch}/
          done

          cd ..

      - name: Update VERSION
        run: echo "${{ needs.check_update.outputs.latest_version }}" > VERSION

      - name: Cleanup tmp
        run: |
          rm -rf tmp
          rm -f frida-gum-devkit-*.tar.xz
          git rm -r --cached tmp || true

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add VERSION android-*
          git commit -m "Update to Frida ${{ needs.check_update.outputs.latest_version }}"
          git push
