name: Update Frida Gum

on:
  schedule:
    - cron: "0 0 * * *" # chạy mỗi ngày 00:00 UTC
  workflow_dispatch: # cho phép chạy thủ công

jobs:
  update-frida:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up jq
        run: sudo apt-get install -y jq

      - name: Get latest Frida version
        id: get_version
        run: |
          VERSION=$(curl -s https://api.github.com/repos/frida/frida/releases/latest | jq -r .tag_name)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Latest version: $VERSION"

      - name: Check current version
        id: check_version
        run: |
          if [ -f VERSION ]; then
            CURRENT=$(cat VERSION)
          else
            CURRENT="none"
          fi
          echo "Current version: $CURRENT"
          echo "CURRENT=$CURRENT" >> $GITHUB_ENV

      - name: Stop if already up to date
        if: env.VERSION == env.CURRENT
        run: |
          echo "Already up-to-date: $VERSION"
          exit 0

      - name: Download Frida Gum devkits
        run: |
          mkdir -p tmp
          cd tmp
          for arch in android-arm android-arm64 android-x86 android-x86_64; do
            url="https://github.com/frida/frida/releases/download/${VERSION}/frida-gum-devkit-${VERSION}-${arch}.tar.xz"
            echo "Downloading $url ..."
            curl -L -O "$url"
            mkdir -p ../$arch
            tar -xf "frida-gum-devkit-${VERSION}-${arch}.tar.xz" -C ../$arch --strip-components=1
          done

      - name: Update VERSION file
        run: echo "${VERSION}" > VERSION

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update Frida Gum Devkit to ${VERSION}" || echo "No changes to commit"
          git push

      - name: Create combined zip
        run: |
          zip -r frida-gum-devkit-${VERSION}-android.zip android-arm android-arm64 android-x86 android-x86_64

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Frida Gum ${{ env.VERSION }}
          body: |
            Auto-generated release for Frida Gum ${{ env.VERSION }}

            Includes prebuilt devkits for:
            - android-arm
            - android-arm64
            - android-x86
            - android-x86_64
          files: |
            frida-gum-devkit-${{ env.VERSION }}-android.zip
